Question 1.
In the code block below, generate 3 normal random variables with mean 100 and standard deviation 1.

This will require about 4 lines of code. Use the functions provided in this outline.

Import the numpy library
Set the seed to 123 to initialize environment so random variables are replicated according to the grader. (hint: np.random.seed(?))
Generate three random normal variables with mean 100 and standard deviation 1 and assign them to a variable named sample. (hint: np.random.normal(?,?,?))
Print the variable sample.


In [1]:
import numpy as np
np.random.seed(123)
samples= np.random.normal(100, 1, 3) # 3 samples are to return
print(samples)


[ 98.9143694  100.99734545 100.2829785 ]


In [11]:
import numpy as np
np.random.seed(121)
samples= np.random.normal(100, 1, 3) # 3 samples are to return
print(samples)


[99.78796683 99.71507083 99.42610179]


Question 2.
Generating random samples from a population lies at the heart of statistics. In the code block below, draw a sample of size 10 from a set containing the integers 1 through 100.

This will require about 5 lines of code. Use the functions provided in this outline.

Import the numpy library
Set the seed to 123 to initialize environment so random variables are replicated according to the grader. (hint: np.random.seed(?))
Create a vector called population, and put the numbers 1-100 into the population list. (hint: np.arange(?,?))
Generate a sample with length 10 from the population. (hint: np.random.choice(?, ?)) and assign the output to a variable named sample.
Print the variable sample.


In [2]:
import numpy as np
np.random.seed(123) #There are many random generators, to use specific we've to mention a specific seed value that is the name of the generator
population = np.arange(1,101)
samples = np.random.choice(population, 10)
print(samples)

[67 93 99 18 84 58 87 98 97 48]


In [3]:
import numpy as np
np.random.seed(122) #There are many random generators, to use specific we've to mention a specific seed value that is the name of the generator
population = np.arange(1,101)
samples = np.random.choice(population, 10)
print(samples)

[27 11 55 77 63 17 16 60 99 80]


In [9]:
import numpy as np
np.random.seed(123) #There are many random generators, to use specific we've to mention a specific seed value that is the name of the generator
population = np.arange(1,101)
samples = np.random.choice(population, 10)
print(samples)

[67 93 99 18 84 58 87 98 97 48]
